// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: api/proto/payment_info.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PaymentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DddBillingAddress int32  `protobuf:"varint,1,opt,name=ddd_billing_address,json=dddBillingAddress,proto3" json:"ddd_billing_address,omitempty"`
	CardholderName    string `protobuf:"bytes,2,opt,name=cardholder_name,json=cardholderName,proto3" json:"cardholder_name,omitempty"`
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_payment_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_info_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentInfo) GetDddBillingAddress() int32 {
	if x != nil {
		return x.DddBillingAddress
	}
	return 0
}

func (x *PaymentInfo) GetCardholderName() string {
	if x != nil {
		return x.CardholderName
	}
	return ""
}

var File_api_proto_payment_info_proto protoreflect.FileDescriptor

var file_api_proto_payment_info_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x61, 0x70, 0x69, 0x22, 0x66, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x13, 0x64, 0x64, 0x64, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x11, 0x64, 0x64, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x61, 0x72, 0x64, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x61, 0x72,
	0x64, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x70,
	0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_payment_info_proto_rawDescOnce sync.Once
	file_api_proto_payment_info_proto_rawDescData = file_api_proto_payment_info_proto_rawDesc
)

func file_api_proto_payment_info_proto_rawDescGZIP() []byte {
	file_api_proto_payment_info_proto_rawDescOnce.Do(func() {
		file_api_proto_payment_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_payment_info_proto_rawDescData)
	})
	return file_api_proto_payment_info_proto_rawDescData
}

var file_api_proto_payment_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_payment_info_proto_goTypes = []interface{}{
	(*PaymentInfo)(nil), // 0: api.PaymentInfo
}
var file_api_proto_payment_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_payment_info_proto_init() }
func file_api_proto_payment_info_proto_init() {
	if File_api_proto_payment_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_payment_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_payment_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_payment_info_proto_goTypes,
		DependencyIndexes: file_api_proto_payment_info_proto_depIdxs,
		MessageInfos:      file_api_proto_payment_info_proto_msgTypes,
	}.Build()
	File_api_proto_payment_info_proto = out.File
	file_api_proto_payment_info_proto_rawDesc = nil
	file_api_proto_payment_info_proto_goTypes = nil
	file_api_proto_payment_info_proto_depIdxs = nil
}
