// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: api/proto/profile.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Profile_Status int32

const (
	Profile_VERIFIED Profile_Status = 0
	Profile_WAITING  Profile_Status = 1
)

// Enum value maps for Profile_Status.
var (
	Profile_Status_name = map[int32]string{
		0: "VERIFIED",
		1: "WAITING",
	}
	Profile_Status_value = map[string]int32{
		"VERIFIED": 0,
		"WAITING":  1,
	}
)

func (x Profile_Status) Enum() *Profile_Status {
	p := new(Profile_Status)
	*p = x
	return p
}

func (x Profile_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Profile_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_profile_proto_enumTypes[0].Descriptor()
}

func (Profile_Status) Type() protoreflect.EnumType {
	return &file_api_proto_profile_proto_enumTypes[0]
}

func (x Profile_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Profile_Status.Descriptor instead.
func (Profile_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_profile_proto_rawDescGZIP(), []int{0, 0}
}

type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Account age in days
	AccountAge int32          `protobuf:"varint,1,opt,name=account_age,json=accountAge,proto3" json:"account_age,omitempty"`
	Ddd        int32          `protobuf:"varint,2,opt,name=ddd,proto3" json:"ddd,omitempty"`
	Status     Profile_Status `protobuf:"varint,3,opt,name=status,proto3,enum=api.Profile_Status" json:"status,omitempty"`
	Name       string         `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Profile) Reset() {
	*x = Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_api_proto_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetAccountAge() int32 {
	if x != nil {
		return x.AccountAge
	}
	return 0
}

func (x *Profile) GetDdd() int32 {
	if x != nil {
		return x.Ddd
	}
	return 0
}

func (x *Profile) GetStatus() Profile_Status {
	if x != nil {
		return x.Status
	}
	return Profile_VERIFIED
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_proto_profile_proto protoreflect.FileDescriptor

var file_api_proto_profile_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0xa2,
	0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x64, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x64, 0x64, 0x12, 0x2b, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x56, 0x45, 0x52, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_profile_proto_rawDescOnce sync.Once
	file_api_proto_profile_proto_rawDescData = file_api_proto_profile_proto_rawDesc
)

func file_api_proto_profile_proto_rawDescGZIP() []byte {
	file_api_proto_profile_proto_rawDescOnce.Do(func() {
		file_api_proto_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_profile_proto_rawDescData)
	})
	return file_api_proto_profile_proto_rawDescData
}

var file_api_proto_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_profile_proto_goTypes = []interface{}{
	(Profile_Status)(0), // 0: api.Profile.Status
	(*Profile)(nil),     // 1: api.Profile
}
var file_api_proto_profile_proto_depIdxs = []int32{
	0, // 0: api.Profile.status:type_name -> api.Profile.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_profile_proto_init() }
func file_api_proto_profile_proto_init() {
	if File_api_proto_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_profile_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_profile_proto_goTypes,
		DependencyIndexes: file_api_proto_profile_proto_depIdxs,
		EnumInfos:         file_api_proto_profile_proto_enumTypes,
		MessageInfos:      file_api_proto_profile_proto_msgTypes,
	}.Build()
	File_api_proto_profile_proto = out.File
	file_api_proto_profile_proto_rawDesc = nil
	file_api_proto_profile_proto_goTypes = nil
	file_api_proto_profile_proto_depIdxs = nil
}
